### ISSUE TITLE
raspberry pi build

### ISSUE THREAD

**Issue by johnelliott** [johnelliott/wb-upload#1]
https://github.com/voodootikigod/node-serialport/issues/342

Problem building on raspberry pi 2 with debian jessie. I created the error simply with the node REPL:

Is there a way to be sure this compiles? I can't tell if mine has compiled on the pi or downloaded a binary that might not work.

> var sp = require('serialport');
> Error: Cannot find module '/home/pi/wb-upload/node_modules/serialport/build/Release/node-v46-linux-arm/serialport.node'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/pi/wb-upload/node_modules/serialport/serialport.js:14:25)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)

**Comment by johnelliott** [comment]
Solution: https://docs.npmjs.com/cli/rebuild
